# Development environment uchun Docker Compose
version: "3.8"

services:
  web:
    build: .
    container_name: survey_web_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: survey_db_dev
    environment:
      POSTGRES_DB: survey_dev_db
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: survey_redis_dev
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: survey_celery_dev
    command: celery -A external_auth_project worker -l debug
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: survey_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data_dev:
