version: "3.8"

services:
  web:
    build: .
    container_name: survey_web
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --worker-class sync --timeout 120 --max-requests 1000 --max-requests-jitter 100 external_auth_project.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:15
    container_name: survey_db
    environment:
      POSTGRES_DB: survey_prod_db
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: your_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: survey_redis
    restart: unless-stopped
    expose:
      - "6379"

  celery:
    build: .
    container_name: survey_celery
    command: celery -A external_auth_project worker -l info --concurrency=2
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0

  nginx:
    image: nginx:latest
    container_name: survey_nginx
    ports:
      - "8085:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
