version: "3.9"

services:
  web:
    build: .
    container_name: survey_web
    command: >
      gunicorn --bind 0.0.0.0:8000 --workers 3 --worker-class sync
      --timeout 120 --max-requests 1000 --max-requests-jitter 100
      external_auth_project.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - survey_network

  db:
    image: postgres:15
    container_name: survey_db
    environment:
      POSTGRES_DB: survey_prod_db
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: super_secret_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - survey_network

  redis:
    image: redis:7-alpine
    container_name: survey_redis
    restart: unless-stopped
    networks:
      - survey_network

  celery:
    build: .
    container_name: survey_celery
    command: celery -A external_auth_project worker -l info --concurrency=2
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: unless-stopped
    networks:
      - survey_network

  nginx:
    image: nginx:latest
    container_name: survey_nginx
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - survey_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  survey_network:
    driver: bridge